### ISSUE TITLE
The  WebView control can't display the map

### ISSUE THREAD

**Issue by LiangJy123** [Azure-Samples/azure-maps-dotnet-webgl-uwp-iot-remote-control#4]
As the title , it's blank on the UWP instead of the map picture.
It only can show the Search-Input-Box .

I try different way to test it .
For example   
-----------
webview.Navigate(new Uri("https://docs.microsoft.com/en-us/azure/azure-maps/map-create"));
------------------------
I want show the web page on my UWP, because it contains the azure maps in that html.

the result is that every control  is ok except the map.

Is there any setting at  the  UWP solution ?

**Comment by rbrundritt** [comment]
I've made some updates to the map code so that it uses the latest version of the map control and waits for the map load event to fire before accessing the map. Can you either get the latest version of this project, or simply get the updated version of the AzureMapsDemo.html.

**Comment by LiangJy123** [comment]
First of all, thank you for your reply so quickly.
------------------------------------------------------------------
Em……It doesn't work after updating the latest version.
The problem is  the Azure maps can't be displayed  on the WebView control.
the AzureMapsDemo.html can be showed by IE.
-----------------------------------------------------------------
I have a project  that  I want to   show the Azure maps on the UWP’s UI.
But the Azure maps only supported on JS.
So I find your solution.

--------------------------------------------------

But the sample problem is also on your solution after I run it.

**Comment by rbrundritt** [comment]
Ok, I believe I know what the issue is. I wen through and made some more updates to the JavaScript, I think it was working before and my update broke it (that's what I get for trying to fix it on my phone, just checked in a fix). The original issue is likely that you are building your app against x86. There was a bug introduced into the UWP WebView last spring in a Windows update which broke WebGL support. I came across this issue myself a few months ago and forgot about it. To get around this, right click on your solution, go to Configuration Manager, and then next to your application, set the platform value to x64.

If the app errors out for you, it likely due to not having the IoT service setup. If you only care about getting the map working, go into the MainPage.xaml.cs file and comment out the code inside the webView_DOMContentLoaded method.

**Comment by LiangJy123** [comment]
Great!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

You are right!
It can display when setting the platform value to x64.

Thank you very very very very very much!
：）
